/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'UK' at '12.05.16 20:24' with Gradle 2.13
 *
 * @author UK, @date 12.05.16 20:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
